### PR TITLE
Update go version to 1.16

### PR DESCRIPTION
**Pull request by jfirebaugh**
This resolves the following warning when using the `release` action:

>         • DEPRECATED: skipped darwin/arm64 build on Go < 1.16 for compatibility, check https://goreleaser.com/deprecations/#builds-for-darwinarm64 for more info.

And the following error:

>    ⨯ release failed after 1503.99s error=failed to build for windows_arm_6: # github.com/terraform-providers/terraform-provider-aws/aws/internal/service/eks/token
aws/internal/service/eks/token/token.go:320:23: undefined: io.ReadAll
note: module requires Go 1.16

As seen in [this run](https://github.com/jfirebaugh/terraform-provider-aws/runs/3109246876).

### CODE REVIEW

**Review by bflad — CHANGES_REQUESTED** [review]
Hi @jfirebaugh 👋  Thank you for submitting this.

Can you please also ensure the following files are updated as well?

- `.github/workflows/test.yml`
- `go.mod` (`go mod tidy` should be ran afterwards for good measure)
- `README.md`

Thanks!

**Comment by bflad** [comment]
Thanks again for this, @jfirebaugh 👍 Since we haven't heard back from you, I've pulled in your commit and the requested changes into a new pull request: #93
